alter reservation
rogierpijpers/Molvena pull request #15
Opened 2018-09-26 11:44 UTC by chestongo

2018-09-26 12:32 UTC, jeroenknoester requested changes
You also have to add this feature in the ReservationService (not only in Repository)

2018-09-26 13:19 UTC, jeroenknoester approved these changes

2018-09-26 13:27 UTC, rogierpijpers requested changes
Compileert niet...

2018-09-28 07:29 UTC, rogierpijpers approved these changes

2018-09-28 11:31 UTC, merged