Mostly ReservationCRUD functionality and some other stuff
rogierpijpers/Molvena pull request #24
Opened 2018-09-28 13:47 UTC by Thomvdm

2018-09-28 16:03 UTC, rogierpijpers reviewed
Ik heb hem niet geblockt maar ook niet approved, changes zijn op zich niet breaking maar kijk dr ff doorheen..

2018-09-28 16:03 UTC, rogierpijpers commented on src/main/resources/static/index.html
> +<script src="js/script.js"></script>
Script tags moeten eigenlijk ín de <html> staan om een valide HTML file te zijn... gelukkig zijn de meeste browsers aardig hufter proof

2018-09-28 16:03 UTC, rogierpijpers commented on src/main/resources/static/index1.html
> +<script src="js/script.js"></script>
Zie bovenstaande, script tags in html

2018-09-28 16:03 UTC, rogierpijpers commented on src/main/resources/static/js/ReservationCRUD.js
> +		.then(function(json){document.getElementById("reservationDisplayText").innerHTML = JSON.stringify(json);
is dit niet tegenwoordig querySelector ipv getElementById?

2018-09-28 16:03 UTC, rogierpijpers commented on src/main/resources/static/js/ReservationCRUD.js
> +						document.getElementById("reservationDisplayText").innerHTML = JSON.stringify(json[reservations]);
zelfde

2018-09-28 16:03 UTC, rogierpijpers commented on src/main/resources/static/js/script.js
> +	document.querySelector(".getReservation").style.visibility = "hidden"
dit kun je in één keer doen, dat is ten slotte waar classes voor zijn. Geeft al bovenstaande elementen bijvoorbeeld de class .reservation, of .toggleable of verzin iets creatiefs

2018-09-28 16:03 UTC, rogierpijpers commented on src/main/resources/static/js/script.js
> +function toggleAccountMenu(){
voor al deze methoden geldt wat ik hier boven zei... probeer het generiek op te lossen

2018-09-28 16:03 UTC, rogierpijpers commented on src/main/resources/static/style.css
> +.menuButtons{
dezefile mag weg? staat niets in..

2018-10-01 10:58 UTC, rogierpijpers approved these changes

2018-10-01 11:10 UTC, jeroenknoester requested changes

2018-10-01 11:10 UTC, jeroenknoester commented on src/main/resources/static/js/ReservationCRUD.js
> +		console.log("input is numeric");
console logs eruit halen?

2018-10-01 12:45 UTC, jeroenknoester approved these changes

2018-10-01 13:59 UTC, merged