Feature/check in
rogierpijpers/Molvena pull request #3
Opened 2018-09-18 13:24 UTC by chestongo

Is this all the functionality we need?

2018-09-18 13:29 UTC, rogierpijpers requested changes
Deze merge staat naar master... dus nee.

2018-09-18 13:30 UTC, rogierpijpers commented on test/com/domain/ReservationTest.java
> +    public void heckInAsReceptionistBeforeEndDate(){
checkin...

2018-09-18 13:31 UTC, rogierpijpers commented on test/com/domain/ReservationTest.java
> +        Date tomorrow = new Date(tomorrowInInt);
gebruik SimpleDateFormat...scheelt een hoop shit

2018-09-18 13:34 UTC, rogierpijpers requested changes

2018-09-18 13:34 UTC, rogierpijpers commented on test/com/domain/ReservationTest.java
> +        reservation.setCheckedIn(true,new Receptionist());
1. Voor mijn intuïtie zou ik .checkIn() zeggen, maar dat is misschien smaak.
2. Ik heb toch mn twijfels bij Receptionist meegeven hier, bij nader inzien is dit geen logische plek om rollen te controleren, of wel? (Is Reservation verantwoordelijk voor het checken van receptionisten?)

2018-09-18 13:36 UTC, rogierpijpers commented on test/com/domain/ReservationTest.java
> +        Assert.assertFalse(reservation.isCheckedIn());
Misschien throw exception als inchecken niet lukt?

https://stackoverflow.com/questions/8423700/how-to-create-a-custom-exception-type-in-java

2018-09-18 13:44 UTC, chestongo commented on test/com/domain/ReservationTest.java
> +        Date tomorrow = new Date(tomorrowInInt);
Slaat nergens op

2018-09-20 11:30 UTC, jeroenknoester approved these changes

2018-09-20 12:42 UTC, rogierpijpers approved these changes

2018-09-20 12:42 UTC, merged