Feature/get available rooms
rogierpijpers/Molvena pull request #4
Opened 2018-09-19 13:39 UTC by jeroengrift

2018-09-19 14:20 UTC, Thomvdm commented on src/com/capgemini/service/ReservationService.java
> +//TODO: add Unit test
Remove

2018-09-19 14:24 UTC, Thomvdm commented on src/com/capgemini/service/ReservationService.java
> +//TODO: give an understandable name
checkone/two/three????

2018-09-19 14:27 UTC, Thomvdm commented on test/com/capgemini/service/ReservationServiceTest.java
> +    public void getAvailableRoomsInsideStartBeforeDateParametersTest() {
Can you clarify this method name?

2018-09-19 14:28 UTC, Thomvdm commented on test/com/capgemini/service/ReservationServiceTest.java
> +    public void getAvailableRoomsInsideEndAfterDateParametersTest() {
Can you clarify method name?

2018-09-19 14:29 UTC, Thomvdm commented on test/com/capgemini/service/ReservationServiceTest.java
> +    public void getAvailableRoomsWithRoomTypeOutside() {
Clarify method name?

2018-09-19 14:29 UTC, Thomvdm commented on test/com/capgemini/service/ReservationServiceTest.java
> +    public void getAvailableRoomsWithWrongRoomTypeOutside() {
Clarify method name?

2018-09-19 14:39 UTC, Thomvdm requested changes
Mooi man. Alleen ff methodetjes en TODOs verwijderen

2018-09-20 09:31 UTC, jeroenknoester approved these changes

2018-09-20 11:04 UTC, closed without merging