Feature/auth folders
rogierpijpers/Molvena pull request #40
Opened 2018-10-08 14:11 UTC by chestongo

2018-10-08 14:26 UTC, rogierpijpers requested changes
Dit werkt nu niet toch? WebSecurityConfig changes wel in dezelfde pull request graag

2018-10-09 14:16 UTC, chestongo commented
Check agian 💃

2018-10-09 14:24 UTC, Thomvdm requested changes

2018-10-09 14:24 UTC, Thomvdm commented on src/main/resources/static/private/receptionist/hotelreservation.html
> +                                        <input type="dFate" class="form-control" id="inputCheckIn" min="" data-error="" required>
Hier gaat wat mis. Dfate?

2018-10-09 14:24 UTC, Thomvdm commented on src/main/resources/static/public/javascript/functions.js
> +            //var count = 0;
unused code

2018-10-09 14:24 UTC, Thomvdm commented on src/main/resources/static/public/javascript/functions.js
> +                //count++;
unused code

2018-10-09 14:24 UTC, Thomvdm commented on src/main/resources/static/public/javascript/functions.js
> +            //var count = 0;
unused code

2018-10-09 14:24 UTC, Thomvdm commented on src/main/resources/static/public/javascript/functions.js
> +                //count++;
unused code

2018-10-09 14:24 UTC, Thomvdm commented on src/main/resources/static/public/javascript/reservation.js
Wil je deze allemaal altijd al vullen bij document.ready, of wanneer je je deze actie begint (maakt met niet veel uit, maar zou op bv de edit knop kunnen)

2018-10-09 14:24 UTC, Thomvdm commented on src/main/resources/static/public/javascript/reservation.js
> +        var reservationID = data.reservationID;
rename data ff, komt op meerdere manieren nu voor

2018-10-10 13:28 UTC, closed without merging