Feature/use chinese characters in guestaccount
rogierpijpers/Molvena pull request #43
Opened 2018-10-09 12:35 UTC by jeroenknoester

2018-10-09 12:38 UTC, Thomvdm commented on src/test/java/com/capgemini/web/GuestControllerTest.java
> +
空白

2018-10-09 12:40 UTC, Thomvdm requested changes

2018-10-09 12:40 UTC, Thomvdm commented on src/test/java/com/capgemini/web/GuestControllerTest.java
> +        guest.setMail("爱@蔼.hk.cn");
普里@阿育王。印度

2018-10-09 12:40 UTC, Thomvdm commented on src/test/java/com/capgemini/web/GuestControllerTest.java
> +        this.mockMvc.perform(get("/guest/爱@蔼.hk.cn"))
普里@阿育王。印度

2018-10-09 14:28 UTC, Thomvdm approved these changes

2018-10-10 07:08 UTC, rogierpijpers approved these changes

2018-10-10 07:09 UTC, merged