Feature/create new homepage
rogierpijpers/Molvena pull request #44
Opened 2018-10-09 12:44 UTC by jeroengrift

2018-10-09 13:10 UTC, chestongo requested changes

2018-10-09 13:10 UTC, chestongo commented on src/main/resources/static/template/js/fillRoomData.js
> +let roomApi = "http://localhost:8080/room/";
roomAPI en api variabelen zelfde?

2018-10-09 13:10 UTC, chestongo commented on src/main/resources/static/template/js/fillRoomData.js
> +    let roomTypeApi = "http://localhost:8080/roomtype/available/";
nvm al aangepast zie ik

2018-10-09 13:10 UTC, chestongo commented on src/main/resources/static/template/js/fillRoomData.js
waarom html in javascript? Je kan ook in javascript een element in een div stoppen met een id. En div hiden via javascript.

2018-10-09 13:37 UTC, chestongo approved these changes

2018-10-10 11:23 UTC, rogierpijpers approved these changes

2018-10-10 11:24 UTC, merged