Feature/guest reservation
rogierpijpers/Molvena pull request #48
Opened 2018-10-10 12:55 UTC by chestongo

2018-10-10 13:53 UTC, rogierpijpers requested changes
conflicts.

2018-10-11 07:01 UTC, rogierpijpers requested changes

2018-10-11 07:01 UTC, rogierpijpers commented on src/main/java/com/capgemini/web/authentication/WebSecurityConfig.java
> -        .antMatchers("/roomtype/available/*/**").permitAll()
Kijk ff wat je merged, niet andersmans code verwijderen graag...

2018-10-11 08:06 UTC, Thomvdm submitted a review, later dismissed

2018-10-11 08:06 UTC, Thomvdm commented on src/main/resources/static/private/admin/admin.html
> +<!DOCTYPE html>
Wat is deze file? Doet dit iets?

2018-10-11 08:06 UTC, Thomvdm commented on src/main/resources/static/private/receptionist/hotelbuilding.html
>      <meta name="description" content="">
hotelbuilding is een hele rare naam, kan dit logischer?

2018-10-11 08:06 UTC, Thomvdm commented on src/main/resources/static/public/javascript/account.js
> +            var newcode = $( "#inputCountry option:selected" ).attr("code");
Maakt voor nu geen zak uit hoor, maar consistentie in camelCasing voorkomt vaak problemen

2018-10-11 08:06 UTC, Thomvdm commented on src/main/resources/static/public/javascript/building.js
> -                alert('success')
Kan deze tekst vervangen worden door een lopende zin? (en ff ; erachter)

2018-10-11 08:06 UTC, Thomvdm commented on src/main/resources/static/public/javascript/fillRoomData.js
> +	window.location.href = "http://localhost:8080/public/guest/all_rooms.html?startDate=" + startDate + "T12:00:00+01:00&endDate=" + endDate + "T12:00:00+01:00&guests=" + amountOfGuests;
Dit is oude code van mij, heb je wel de goede branche gepulled?

2018-10-11 08:06 UTC, Thomvdm commented on src/main/resources/static/public/javascript/reservation.js
> +                          "room": room
Het lijkt alsof Room een enkel char als variabele heeft. Hoe werkt dit?

2018-10-11 09:16 UTC, rogierpijpers approved these changes

2018-10-11 09:33 UTC, jeroengrift approved these changes

2018-10-11 09:35 UTC, merged