Added isloggedin functionality
rogierpijpers/Molvena pull request #52
Opened 2018-10-10 14:37 UTC by Thomvdm

2018-10-10 16:40 UTC, rogierpijpers requested changes
Die .equals() even aanpassen is wel belangrijk, de rest is smaak.

2018-10-10 16:40 UTC, rogierpijpers commented on src/main/java/com/capgemini/web/AccountController.java
> +        boolean isLoggedIn = AuthenticationHelper.isLoggedIn();
return AuthenticationHelper.isLoggedIn() kan ook toch? Scheelt weer een regel

2018-10-10 16:40 UTC, rogierpijpers commented on src/main/java/com/capgemini/web/authentication/AuthenticationHelper.java
> +        if (auth.getPrincipal() == "anonymousUser"){
1. Strings vergelijken met .equals() graag, dit is geen garantie

2. Niet zo belangrijk, maar je zou ook het hele if else statement weg kunnen halen en het volgende doen:
return auth.getPrincipal().equals("anonymousUser");

2018-10-11 09:36 UTC, rogierpijpers approved these changes

2018-10-11 09:36 UTC, jeroenknoester approved these changes

2018-10-11 09:36 UTC, merged