Feature/delete reservation
rogierpijpers/Molvena pull request #6
Opened 2018-09-20 12:47 UTC by chestongo

2018-09-20 12:56 UTC, rogierpijpers requested changes
Alsjeblieft zonder alle .idea files.. heb ze net op de gitignore in develop gekregen.

2018-09-20 13:12 UTC, rogierpijpers requested changes

2018-09-20 13:12 UTC, rogierpijpers commented on src/com/capgemini/service/ReservationService.java
> +    private void setSoftDelete(int reservationID){
is geen setter in principe.. dus ik zou hem "delete" of eventueel "softDelete" noemen

2018-09-20 13:12 UTC, rogierpijpers commented on src/com/capgemini/service/ReservationService.java
> +        for(Reservation reservation : reservationRepository.getAllReservations()){
Dit hele stuk zou vervangen kunnen worden met een reservationRepository.getReservationById() methode..

2018-09-20 13:12 UTC, rogierpijpers commented on src/com/capgemini/service/ReservationService.java
> +                System.out.println("No reservations found");
Liever geen system.out.println in productie code..

2018-09-20 13:39 UTC, rogierpijpers submitted a review, later dismissed

2018-09-20 13:39 UTC, rogierpijpers commented on src/com/capgemini/service/ReservationService.java
> +    private void SoftDelete(int reservationID){
parameter Reservation reservation lijkt me een betere parameter, in plaats van ID meegeven

2018-09-20 13:39 UTC, rogierpijpers commented on src/com/capgemini/service/ReservationService.java
> +    private void SoftDelete(int reservationID){
functie naam begint altijd met kleine letter

2018-09-21 11:08 UTC, rogierpijpers requested changes
1. Waar zijn de unit tests?
2. Pull develop even in je branch, er zijn merge conflicts...

2018-09-21 12:36 UTC, rogierpijpers approved these changes

2018-09-21 12:37 UTC, jeroenknoester approved these changes

2018-09-21 12:37 UTC, merged